#!/usr/bin/env sh

set -e

cmd_options=$*
# TODO: have an array and iterate over
login="<username>@<sub-domain.domain.com>"

time rsync -zrt --delete . ${login}:/var/chef > /tmp/chef-rsync.log 2>&1
echo '[INFO] sync done'

ssh ${login} "chef-solo $cmd_options -c /var/chef/solo.rb"
