#!/usr/bin/env sh

set -e

cmd_options=$*
# TODO: have an array and iterate over
login="<username>@<sub-domain.domain.com>"

rsync -r . ${login}:/var/chef
echo 'sync done'

ssh ${login} "chef-solo $cmd_options -c /var/chef/solo.rb"
